--DROP TABLE WORD;
CREATE TABLE WORD (
    ID SERIAL PRIMARY KEY,
    TEXT VARCHAR(50) NOT NULL
);

--DROP TABLE CATEGORY;
CREATE TABLE CATEGORY (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

--DROP TABLE ROOM;
CREATE TABLE ROOM (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    STATE VARCHAR(20) NOT NULL,
    ID_CATEGORY INT,
    FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID)
);

--DROP TABLE WORD_CATEGORY;
CREATE TABLE WORD_CATEGORY (
    ID SERIAL PRIMARY KEY,
    ID_WORD INT,
    ID_CATEGORY INT,
    FOREIGN KEY (ID_WORD) REFERENCES WORD(ID),
    FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID)
);